version: "3.8"

services:

  blue:
    build: ./blue
    container_name: blue-app
    environment:
      - SERVER_PORT=80

  green:
    build: ./green
    container_name: green-app
    environment:
      - SERVER_PORT=80

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green

  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
