events {}

http {
    upstream app {
        server blue:80;   # 🔵 Initially LIVE
        # server green:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }
    }
}
